#!/usr/local/bin/python3

from database import Database
import models
import os

dsn_pg = os.getenv("POSTGRESQL_DSN")
pg_password_file = os.getenv("POSTGRESQL_PASSWORD_FILE")
dsn_mariadb = os.getenv("MARIADB_DSN")
mariadb_password_file = os.getenv("MARIADB_PASSWORD_FILE")

with Database(dsn_pg, pg_password_file) as pg, Database(dsn_mariadb, mariadb_password_file) as mariadb:
    def apply_action(action, model, old=None) -> bool:
        class_model = model.__class__

        if (old == None):
            old = mariadb.exec(mariadb.select(class_model).where(class_model.external_id == model.external_id)).first()

        match action:
            case "DELETE":
                if (old):
                    mariadb.delete(old, commit=True)

            case "INSERT":
                if (old):
                    print(f"{class_model.__name__} already exist. Forward to UPDATE.")
                    apply_action("UPDATE", model, old)
                else:
                    mariadb.insert(model, commit=True)

            case "UPDATE":
                if (old != model):
                    if (old):
                        old.update(model)
                        mariadb.add(old, commit=True)
                    else:
                        print(f"{class_model.__name__} not exist. Forward to INSERT.")
                        apply_action("INSERT", model, False)
                else:
                    print(f"Both items are same: {old} -> {model}")

    pg_statement = pg.select(models.ResPartnerAudit)
    result = pg.exec(pg_statement)

    for row in result:
        contact = models.Contact(
            external_id=row.partner_id,
            name=row.data["name"],
            email=row.data["email"]
        )

        apply_action(row.action, contact)
        pg.delete(row, commit=True)
